//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bàn
    {
        public int Số_bàn { get; set; }
        public string Tên_bàn { get; set; }
        public string Trạng_thái { get; set; }
    }
}
