//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hóa_đơn_bán
    {
        public int Mã_HĐ { get; set; }
        public int Mã_sản_phẩm { get; set; }
        public Nullable<System.DateTime> Ngày_xuất_HĐ { get; set; }
        public int Mã_nhân_viên { get; set; }
        public Nullable<int> Ngày_xuất { get; set; }
        public Nullable<int> Số_lượng { get; set; }
    
        public virtual Nhân_viên Nhân_viên { get; set; }
        public virtual Sản_phẩm Sản_phẩm { get; set; }
    }
}
