//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhân_viên
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhân_viên()
        {
            this.Hóa_đơn_bán = new HashSet<Hóa_đơn_bán>();
        }
    
        public int Mã_nhân_viên { get; set; }
        public string Tên_nhân_viên { get; set; }
        public Nullable<System.DateTime> Ngày_vào_làm { get; set; }
        public string Vị_trí { get; set; }
        public string Hình { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hóa_đơn_bán> Hóa_đơn_bán { get; set; }
    }
}
