//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sản_phẩm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sản_phẩm()
        {
            this.Hóa_đơn_bán = new HashSet<Hóa_đơn_bán>();
        }
    
        public int Mã_sản_phẩm { get; set; }
        public string Tên_sản_phẩm { get; set; }
        public Nullable<decimal> Giá_gốc { get; set; }
        public Nullable<decimal> Giá_bán { get; set; }
        public string Hình { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hóa_đơn_bán> Hóa_đơn_bán { get; set; }
    }
}
